# Puerto del microservicio
server.port=8081

# Nombre de la aplicación
spring.application.name=poliza-service

# Configuración de R2DBC para H2
spring.r2dbc.url=r2dbc:h2:mem:///polizasdb
spring.r2dbc.username=sa
spring.r2dbc.password=

spring.sql.init.mode=always