CREATE TABLE IF NOT EXISTS POLIZAS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NUMERO_POLIZA VARCHAR(50) NOT NULL UNIQUE,
    DNI_CLIENTE VARCHAR(20) NOT NULL,
    ESTADO VARCHAR(20) NOT NULL,
    MONTO_COBERTURA DECIMAL(15, 2) NOT NULL
    );

INSERT INTO POLIZAS (NUMERO_POLIZA, DNI_CLIENTE, ESTADO, MONTO_COBERTURA)
VALUES ('POL-1001', '70123456', 'ACTIVA', 50000.00);

INSERT INTO POLIZAS (NUMERO_POLIZA, DNI_CLIENTE, ESTADO, MONTO_COBERTURA)
VALUES ('POL-1002', '70987654', 'VENCIDA', 25000.00);